"""add availability slots

Revision ID: 9b351f287ad0
Revises: b5370d742305
Create Date: 2026-04-13 18:34:10.218612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b351f287ad0'
down_revision = 'b5370d742305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availability_slot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availability_slot_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('swap_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proposed_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swap_request', schema=None) as batch_op:
        batch_op.drop_column('proposed_time')

    with op.batch_alter_table('availability_slot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availability_slot_user_id'))

    op.drop_table('availability_slot')
    # ### end Alembic commands ###
