"""add portfolio

Revision ID: ff3ebdd6ad70
Revises: 9b351f287ad0
Create Date: 2026-04-13 18:53:11.381740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff3ebdd6ad70'
down_revision = '9b351f287ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_url', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_project_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('portfolio_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('portfolio_url')
        batch_op.drop_column('linkedin_url')
        batch_op.drop_column('github_username')

    with op.batch_alter_table('portfolio_project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_project_user_id'))

    op.drop_table('portfolio_project')
    # ### end Alembic commands ###
